import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { forkJoin, Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class MockDataService {
  constructor(private http: HttpClient) {}

  // Added 'historical' to the returned object
  loadAll(): Observable<{ routes: any[]; drivers: any[]; historical: any[] }> {
    return forkJoin({
      routes: this.http.get<any[]>('assets/routes.json'),
      drivers: this.http.get<any[]>('assets/drivers.json'),
      // NEW: Points to the file generated by your Python script
      historical: this.http.get<any[]>('assets/mock-data/historical-stats.json')
    });
  }
}
